name: Flutter CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.x'
      - run: cd hasad/mobile && flutter pub get
      - run: cd hasad/mobile && dart format --set-exit-if-changed .
      - run: cd hasad/mobile && flutter analyze
      - run: cd hasad/mobile && flutter test
